services:
  template-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PROJECT_NAME:-template}:web-dev
    container_name: ${PROJECT_NAME:-template}-web-dev
    working_dir: /var/www/html
    ports:
      - '${APP_PORT:-8081}:8001'
    volumes:
      - .:/var/www/html
    depends_on:
      - ${PROJECT_NAME:-template}-db

  template-db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME:-template}-db-dev
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-template}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-template}
      MYSQL_ROOT_HOST: '%'
      TZ: ${APP_TIMEZONE:-America/Sao_Paulo}
    ports:
      - '${DB_FORWARD_PORT:-3306}:3306'
    volumes:
      - ${PROJECT_NAME:-template}-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  template-db:
    name: ${PROJECT_NAME:-template}-db-dev